
services:

  ## SIMPLE LOGIN
  ## ============
  
  postgres:
    image: postgres:12.1
    container_name: sl-db
    env_file: .env
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      retries: 3
      start_period: 1s
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: unless-stopped

  migration:
    image: simplelogin/$SL_IMAGE:$SL_VERSION
    command: [ "alembic", "upgrade", "head" ]
    container_name: sl-migration
    env_file: .env
    volumes:
      - ./pgp:/sl/pgp
      - ./upload:/code/static/upload
      - ./dkim.key:/dkim.key
      - ./dkim.pub.key:/dkim.pub.key
    depends_on:
      postgres:
        condition: service_healthy

  init:
    image: simplelogin/$SL_IMAGE:$SL_VERSION
    command: [ "python", "init_app.py" ]
    container_name: sl-init
    env_file: .env
    volumes:
      - ./pgp:/sl/pgp
      - ./upload:/code/static/upload
      - ./dkim.key:/dkim.key
      - ./dkim.pub.key:/dkim.pub.key
    depends_on:
      migration:
        condition: service_completed_successfully

  app:
    image: simplelogin/$SL_IMAGE:$SL_VERSION
    container_name: sl-app
    env_file: .env
    volumes:
      - ./pgp:/sl/pgp
      - ./upload:/code/static/upload
      - ./dkim.key:/dkim.key
      - ./dkim.pub.key:/dkim.pub.key
    networks:
      - traefik
      - default
    restart: unless-stopped
    depends_on:
      init:
        condition: service_completed_successfully
    labels:
      - traefik.enable=true
      - traefik.http.services.sl-app.loadbalancer.server.port=7777
      - traefik.http.routers.sl-app.service=sl-app
      - traefik.http.routers.sl-app.middlewares=sts
      - traefik.http.routers.sl-app.rule=Host("${SUBDOMAIN:-app}.${DOMAIN:?DOMAIN_not_set}")
      - traefik.http.routers.sl-app.tls.certresolver=${LE_CHALLENGE:-tls}
      ## redirect http(s)://$DOMAIN -> https://$SUBDOMAIN.$DOMAIN
      - traefik.http.routers.${LE_CHALLENGE:-tls}.rule=Host("${DOMAIN}")
      - traefik.http.routers.${LE_CHALLENGE:-tls}.tls.certresolver=${LE_CHALLENGE:-tls}
      - traefik.http.routers.dns.tls.domains[0].main=${DOMAIN}
      - traefik.http.routers.dns.tls.domains[0].sans=*.${DOMAIN}
      - traefik.http.routers.${LE_CHALLENGE:-tls}.middlewares=redir,sts
      - traefik.http.middlewares.redir.redirectregex.regex=^https?://${DOMAIN}/?.*
      - traefik.http.middlewares.redir.redirectregex.replacement=https://${SUBDOMAIN:-app}.${DOMAIN}
      ## add STS Header for $DOMAIN and all subdomains
      - traefik.http.middlewares.sts.headers.stsSeconds=31536000
      - traefik.http.middlewares.sts.headers.sslRedirect=true
      - traefik.http.middlewares.sts.headers.forceSTSHeader=true 
      - traefik.http.middlewares.sts.headers.stsPreload=true
      - traefik.http.middlewares.sts.headers.stsIncludeSubdomains=true
      ## static response for `mta-sts` subdomain 
      - traefik.http.routers.mta-sts.rule=Host("mta-sts.${DOMAIN}") && PathPrefix("/.well-known/mta-sts.txt")
      - traefik.http.routers.mta-sts.service=noop@internal
      - traefik.http.routers.mta-sts.middlewares=mta-sts
      - traefik.http.middlewares.mta-sts.plugin.staticresponse.StatusCode=200
      - "traefik.http.middlewares.mta-sts.plugin.staticresponse.Body=version: STSv1\nmode: testing\nmx: ${SUBDOMAIN:-app}.${DOMAIN}\nmax_age: 86400"
      ## Note: The following parameters have to be set in traefik static config, to activate `staticresponse` plugin:
      # experimental.plugins.staticresponse.moduleName=github.com/jdel/staticresponse
      # experimental.plugins.staticresponse.version=v0.0.1

  email:
    image: simplelogin/$SL_IMAGE:$SL_VERSION
    command: ["python", "email_handler.py"]
    container_name: sl-email
    env_file: .env
    volumes:
      - ./pgp:/sl/pgp
      - ./upload:/code/static/upload
      - ./dkim.key:/dkim.key
      - ./dkim.pub.key:/dkim.pub.key
    restart: unless-stopped
    depends_on:
      init:
        condition: service_completed_successfully

  job-runner:
    image: simplelogin/$SL_IMAGE:$SL_VERSION
    command: ["python", "job_runner.py"]
    container_name: sl-job-runner
    env_file: .env
    volumes:
      - ./pgp:/sl/pgp
      - ./upload:/code/static/upload
      - ./dkim.key:/dkim.key
      - ./dkim.pub.key:/dkim.pub.key
    restart: unless-stopped
    depends_on:
      init:
        condition: service_completed_successfully
